return {}
-- {
--   "yetone/avante.nvim",
--   build = "make",
--   event = "VeryLazy",
--   version = false,
--   ---@module 'avante'
--   ---@type avante.Config
--   opts = {
--     instructions_file = "avante.md",
--     provider = "claude",
--     providers = {
--       claude = {
--         endpoint = "https://api.anthropic.com",
--         model = "claude-sonnet-4-20250514",
--         api_key_name = "cmd:pass anthropic/api-key",
--         timeout = 30000,
--         extra_request_body = {
--           temperature = 0.75,
--           max_tokens = 20480,
--         },
--       },
--     },
--   },
--   dependencies = {
--     "nvim-lua/plenary.nvim",
--     "MunifTanjim/nui.nvim",
--     "nvim-telescope/telescope.nvim",
--     "hrsh7th/nvim-cmp",
--     "nvim-tree/nvim-web-devicons",
--     {
--       "MeanderingProgrammer/render-markdown.nvim",
--       opts = {
--         file_types = { "markdown", "Avante" },
--       },
--       ft = { "markdown", "Avante" },
--     },
--   },
-- }
