return {}
--   "olimorris/codecompanion.nvim",
--   dependencies = {
--     "nvim-lua/plenary.nvim",
--     "nvim-treesitter/nvim-treesitter",
--   },
--   opts = {
--     -- NOTE: The log_level is in `opts.opts`
--     opts = {
--       log_level = "DEBUG", -- or "TRACE"
--     },
--   },
--   config = function()
--     require("codecompanion").setup {
--       adapters = {
--         anthropic = require("codecompanion.adapters").use("anthropic", {
--           env = {
--             api_key = "ANTHROPIC_API_KEY",
--           },
--         }),
--       },
--     }
--   end,
-- }
