return {}
-- {
--   "olimorris/codecompanion.nvim",
--   event = "VeryLazy",
--   dependencies = {
--     "nvim-lua/plenary.nvim",
--     "nvim-treesitter/nvim-treesitter",
--   },
--   opts = {
--     adapters = {
--       anthropic = function()
--         return require("codecompanion.adapters").extend("anthropic", {
--           env = {
--             api_key = "cmd:pass anthropic/api-key",
--           },
--         })
--       end,
--     },
--     strategies = {
--       chat = { adapter = "anthropic" },
--       inline = { adapter = "anthropic" },
--     },
--   },
-- }
